### ISSUE TITLE
Non-critical NPE when opening a JSON file with this plugin

### ISSUE THREAD

**Issue by adam-funk** [GateNLP/gateplugin-Format_JSON#3]
Whenever I open a JSON file with this plugin, I get this in Messages:

```java.lang.NullPointerException
	at javax.activation.MimeType.parse(MimeType.java:97)
	at javax.activation.MimeType.<init>(MimeType.java:63)
	at gate.corpora.MimeType.<init>(MimeType.java:42)
	at gate.corpora.GATEJSONFormat.unpackMarkup(GATEJSONFormat.java:93)
	at gate.corpora.DocumentImpl.init(DocumentImpl.java:315)
	at gate.Factory.createResource(Factory.java:430)
	at gate.gui.NewResourceDialog$4.run(NewResourceDialog.java:270)
	at java.lang.Thread.run(Thread.java:748)
```

It happens again with each new document. As far as I can tell, the documents are loading correctly anyway.

**Comment by greenwoodma** [comment]
how exactly are you loading documents when this happens? I'm asking because I can't see how this could happen and the document load correctly using the JSON format. The only reason for an NPE here is if no mimetype has been set for the document you are loading.

I guess my question is, are you specifying a mimetype or relying on file extension to trigger usage of the JSON document format.

**Comment by adam-funk** [comment]
I was opening local files and relying on the file extension (not filling in the mimeType doc parameter). 
But that works in GATE for most files with correct filename extensions without setting mimeType or getting an error message.

**Comment by greenwoodma** [comment]
cool, at least that makes sense. I guess I probably need a sensible null check on the mimetype somewhere (I don't think I've ever relied on the file extension with the json format)
